### ISSUE TITLE
[REQ] Improve .umi Format

### ISSUE THREAD

**Issue by SeppFS** [unimarkup/unimarkup-rs#121]
## Is your feature request related to other issues/PRs?
#116 

## Describe the solution you'd like
- [x] Improve Resilience of Rendering / Parsing
- [x] Move Language-Independent Attributes to A New 'Properties' Column
- [x] Print Preamble instead of Config and do not deserialize default Attributes
- [x] Remove Spans
- [x] Add Test Cases
- [x] Use Input from Config to Determine FileType and Parse Correct Locale Language
- [x] Output Input Path to .umi (somewhere)

## Additional context

Currently, .umi can be rendered and parsed, but the structure has to be cleaned up and improved.

**Comment by mhatzl** [comment]
Some additional points that should be part of this issue:

- the preamble row should only contain non-default values

  Having „None“ values serialized looks quite bade in the output.
  e.g. „author: ~“
  Not sure how we can achieve this without much hassle.

- the preamble must be treated like a regular block

  Meaning that it has its own row with kind „Preamble“. This is needed, because preambles may be adapted depending on i18n. 

- remove spans in the attribute section

  We decided internally that this information only increases complexity. Spans are only helpful for error messages and highlighting for .um files, because .umi file rows cannot be easily mapped to span lines.
